##
## Makefile for  in /home/planch_j/rendu/Info/gfx_raytracer1/
##
## Made by Jean PLANCHER
## Login   <planch_j@epitech.net>
##
## Started on  Mon Feb 22 18:22:47 2016 Jean PLANCHER
## Last update Mon May 16 15:46:11 2016 Jean PLANCHER
##

all:
	make -C create_scene

clean:
	make clean -C create_scene

fclean: clean
	make fclean -C create_scene

re: fclean all

.PHONY: all clean fclean re
